TITLE_FONT = ("Electrolize", "11", "bold")
ADD_FONT = ('Electrolize', '12', "bold")
DEL_FONT = ('Electrolize', '12', "bold")
HURT_FONT = ('Electrolize', '8', "bold")
DV_FONT = ("Electrolize", "15", "bold")