SMALL_ENTRY_SIZE = 5
MED_ENTRY_SIZE = 20
COMPONENT_PADDING = 10

DEL_BUTTON_BD = 5
DEL_BUTTON_WIDTH = 20

CANCEL_BUTTON_SUBSAMPLE = 4
CONFIRM_BUTTON_SUBSAMPLE = 4

CONDITIONS_COLUMNS = 4

COMPONENT_FRAME_BD = 2

TYPE_SELECTOR_WIDTH = 13
TARGET_SELECTOR_WIDTH = 5
